### ISSUE TITLE
Morning team code review

### ISSUE THREAD

**Issue by aliabbani** [medaminedev66/Conference-page#2]
# The project is actually really good 💯 💥 
Hi Amine you have really done a great job but we think as a group reviewing your code you can still improve your project though on some aspects like : 
## add ⬆️ 

*  in the about page, the past activity h2 is better to be centered.
*  in the about page - in the navbar, the sponsor link, it's better to be linked to the partner's section.
*  in the about page - in the navbar, the logo should be linked to the home page.
* I think some of the images are not loading up. It has to do with your image URL. Kindly try to add the correct file paths with "./" or "../" preceding them to see if it works.
* You may consider changing the size of the logo at the footer part of the mobile home page. The display is currently not appealing to me in particular. I don't know how it looks for you but I strongly suggest you reduce the size of the image to make the text lines longer.
* below the program section, the see the hole program should be 'see whole program'
* The nav link should be adjusted properly

**Comment by medaminedev66** [comment]
Thanks to my friends for all these suggestions, I worked on all of them, and I improved my website interface.
